### ISSUE TITLE
Caching options

### ISSUE THREAD

**Issue by dhollema** [koopjs/koop-output-vector-tiles#13]
I see vector tiles output uses an in-memory cache. 

- Architecturally, is this the same caching layer as [cache plugins](https://koopjs.github.io/docs/available-plugins/caches)?
- Are other caching options available beyond an in-memory cache?

**Comment by rgwozdz** [comment]
Yes, the in-memory cache is just the default cache plugin.  The other option that is currently maintained and up to date is the [Redis cache plugin](https://github.com/koopjs/koop-cache-redis).

**Comment by dhollema** [comment]
So I understand, the [Redis cache plugin](https://github.com/koopjs/koop-cache-redis) can serve as a substitute to the [tile-sets-cache](https://github.com/koopjs/koop-output-vector-tiles/blob/master/src/tile-sets-cache.js)?

**Comment by rgwozdz** [comment]
Sorry, I misread/misunderstood your question; the tile-sets-cache is _not_ the same as the cache-plugin.  The cache-plugin just caches provider data.  For caching tiles, there is currently no other option.

You could use NGINX to cache tiles for a certain period of time; this is pretty common for OSM servers.

**Comment by dhollema** [comment]
Makes sense, thank you.
