### ISSUE TITLE
a demo for vector-tiles with geojson file provider please

### ISSUE THREAD

**Issue by mapsgeek** [koopjs/koop-output-vector-tiles#5]

**Comment by rgwozdz** [comment]
@mapsgeek - interested in submitting a PR?  We're always looking for contributors.

**Comment by mapsgeek** [comment]
@rgwozdz  sorry for not providing a description, i used to serve vector-tiles from mbtiles built from a geojson source using tippecanoe, but with koopjs as i understand it can serve MVT directly from geojson and also query the geojson file as static file from a directory ! which is awesome but i can't get it to set up both the vectore-tiles and geojson-file together and that's what i'm seeking help for.

**Comment by mapsgeek** [comment]
sorry for inconvenience i managed to edit the demo in the repo to get it working i took a while to grasp the concept of providers and output

**Comment by ajturner** [comment]
@mapsgeek any suggestions for the documentation or terminology to make it easier to understand or setup?

**Comment by mapsgeek** [comment]
@ajturner thank you it's actually straight forward naming, and things gets clarified when you read the Koop Core Usage section in the docs before diving into the plugins, maybe making this a part of the homepage or changing the order of section can help a bit.

**Comment by adamajm** [comment]
@mapsgeek - are you suggesting pushing https://koopjs.github.io/docs/usage/koop-core or https://koopjs.github.io/docs/basics/overview closer to the 'front'?

**Comment by mapsgeek** [comment]
yes push the koop-core section to be under the overview, because it's more logical as a sequence and even in the overview itself you mention the core first then providers and outputs etc ..
